# [target.'cfg(target_arch = "riscv32")']
# rustflags = [
#   "-C", "link-arg=-Tlinkall.x",
#   "-C", "force-frame-pointers",
# ]

# [target.'cfg(target_arch = "xtensa")']
# rustflags = [
#   # GNU LD
#   "-C", "link-arg=-Wl,-Tlinkall.x",
#   "-C", "link-arg=-nostartfiles",

#   # LLD
#   # "-C", "link-arg=-Tlinkall.x",
#   # "-C", "linker=rust-lld",
# ]

[target.riscv32imac-esp-espidf]
rustflags = ["--cfg", "espidf_time64"]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = ".github/config/sdkconfig.defaults"
ESP_IDF_VERSION = "v5.3.2"